title: "My Cybersecurity Portfolio"
description: "Showcasing my cybersecurity projects and knowledge."
theme: minima  # You can change this to another Jekyll theme
baseurl: "/Cybersecurity-Portfolio"
url: "https://maplecheeze.github.io"

